zincati-update-now: give good error message when run without privs
This is a bit better than what currently happens.

diff --git a/dist/bin/zincati-update-now b/dist/bin/zincati-update-now
--- a/dist/bin/zincati-update-now
+++ b/dist/bin/zincati-update-now
@@ -3,6 +3,11 @@ set -euo pipefail
 
 echo "WARN: This command is experimental and subject to change." >&2
 
+if [ "$EUID" != "0" ]; then
+    echo "ERROR: Must be root to run zincati-update-now" >&2
+    exit 1
+fi
+
 # this should exist already, but in case
 mkdir -p /run/zincati/config.d
 cat > /run/zincati/config.d/99-update-now.toml << EOF
